# -*- mode: ruby -*-
# vi: set ft=ruby :

# This will set up the two VMs required to run the EPC and RAN
# It will:
# => Add bridged and internal networks
# => Set IP address and routing
# => Add IP forwarding to EPC to allow traffic to flow to the core
# Later, I will add:
# => Mininet, BMV2
# => Separate docker containers from bridged network
# => Connect containers to software switch as a bridge
# => Implement P4 to test in-band network monitoring

Vagrant.configure("2") do |config|
  config.vm.define "epc" do |epc|
    # Using Ubuntu 18.04 Bionic Beaver
    epc.vm.box = "ubuntu/bionic64"

    # Using vagrant-disksize plugin
    epc.disksize.size = '50GB'

    # set name, ram, cpus
    epc.vm.provider "virtualbox" do |v|
      v.name = "epc"
      v.memory = 4096
      v.cpus = 2
    end

    epc.vm.network "private_network", ip: "10.10.1.2", virtualbox__intnet: true

    # Install required packages and build binaries
    epc.vm.provision "shell", path: "scripts/bootstrap_epc.sh"
    # NOTE: Deprecated provision-statement, do not use, should be removed later. 
    # epc.vm.provision "shell", privileged: false, path: "scripts/user_epc.sh"
  end

  config.vm.define "ran" do |ran|
    # Using Ubuntu 18.04 Bionic Beaver
    ran.vm.box = "ubuntu/bionic64"

    # Using vagrant-disksize plugin
    ran.disksize.size = '20GB'

    # set name, ram, cpus
    ran.vm.provider "virtualbox" do |v|
      v.name = "ran"
      v.memory = 4096
      v.cpus = 2
    end

    # .1 addresses are usually not suggested, but it will be fine in this case, easily changed later
    ran.vm.network "private_network", ip: "10.10.1.1", virtualbox__intnet: true

    # Install required packages and build binaries
    ran.vm.provision "shell", path: "scripts/bootstrap_ran.sh"
    ran.vm.provision "shell", path: "scripts/user_ran.sh"

    # Copy and move config files to correct locations
    ran.vm.provision "file", source: "config/rcc.band7.tm1.nfapi.conf", destination: "~/"
    ran.vm.provision "shell", inline: "mv /home/vagrant/rcc.band7.tm1.nfapi.conf /home/netmon/src/enb_folder/ci-scripts/conf_files/"

    ran.vm.provision "file", source: "config/ue_eurecom_test_sfr.conf", destination: "~/"
    ran.vm.provision "shell", inline: "mv /home/vagrant/ue_eurecom_test_sfr.conf /home/netmon/src/ue_folder/openair3/NAS/TOOLS/"

    ran.vm.provision "file", source: "config/ue.nfapi.conf", destination: "~/"
    ran.vm.provision "shell", inline:  "mv /home/vagrant/ue.nfapi.conf /home/netmon/src/ue_folder/ci-scripts/conf_files/"

  end

  config.vm.define "p4ovs" do |p4ovs|
    # Using Ubuntu 20.10 Groovy Gorilla
    p4ovs.vm.box = "ubuntu/groovy64"

    # Using vagrant-disksize plugin
    p4ovs.disksize.size = '30GB'

    # set name, ram, cpus
    p4ovs.vm.provider "virtualbox" do |v|
      v.name = "p4ovs"
      v.memory = 4096
      v.cpus = 2
    end

    # Gonna use as switch to connect EPC and RAN
    p4ovs.vm.network "private_network", ip: "10.10.1.3", virtualbox__intnet: true

    # Compile P4-OvS
    p4ovs.vm.provision "shell", path: "scripts/bootstrap_p4ovs.sh"
  end
end
